"
" Note: These lines must come first!
" Note: I found some good tips at https://github.com/samnang/dotfiles/blob/master/vimrc
"
" DO NOT ADD CHANGES HERE UNLESS THEY ARE UNIVERSAL.
" Otherwise, add them in a file called ~/.local.bashrc which this script
" sources.
set nocompatible
filetype off

"
" VUNDLE BUNDLES
"
" Note: These lines allow vundle to work. On a new installation,
"       you may get the message saying vundle#rc() is not defined.
"       In this case, run:
"
"           git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
"
"       This is from https://github.com/gmarik/vundle
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..
"
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'
" BEGIN: Vundle bundles
Bundle 'https://github.com/kien/ctrlp.vim'
Bundle 'https://github.com/ciaranm/inkpot.git'
Bundle 'https://github.com/cespare/zenburn.git'
Bundle 'https://github.com/vim-ruby/vim-ruby'
Bundle 'https://github.com/pangloss/vim-javascript'
Bundle 'https://github.com/othree/html5.vim'
" END: Vundle bundles


set encoding=utf-8
syntax enable
filetype plugin indent on  " load file type plugins + indentation

set showmode  " display what mode we're in
set showmatch  " show matching brackets/parentheses

set nowrap  " do not wrap 
set tabstop=2 shiftwidth=2  " a tab is two spaces
set expandtab  " use spaces instead of tab characters
autocmd FileType Makefile set noexpandtab
set autoindent  " match indentation of previous line
" set smartindent  " indent based on brackets

set hlsearch  " highlight search terms
set ignorecase smartcase  " Ignore case if entire search term is lower case

set list listchars=tab:»\ ,trail:·  " show tabs and trailing spaces
hi SpecialKey ctermfg=Red

set hidden
set title
set number
set ruler
"set cursorline  " underline the line with the cursor
set history=1000  " make history huge

set nobackup nowritebackup  " No backup files before overwriting
set directory=~/.vim/tmp  " keep swap files in one location

"
" gvim-specific settings
"
if has('gui_running')
  " gvim only
  set lines=65
  colorscheme desert
endif


" Note to self: Remember previous google-specific stuff was at ~/.vimrc-google.
if filereadable("~/.local.vimrc")
  source ~/.local.vimrc
end
